[google_sheets]
type = "service_account"
project_id = "driven-actor-456302-e7"
private_key_id = "d2b9e128b902b2df59d4ab3cdebf920e0811cc17"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqTXHGEVORd4MB
...
cWiknrcg4sUorYVMdvMcR7M=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets@driven-actor-456302-e7.iam.gserviceaccount.com"
client_id = "114375121378848295396"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets@driven-actor-456302-e7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
