[google_sheets]
type = "service_account"
project_id = "driven-actor-456302-e7"
private_key_id = "0685f1fbade4b5e26b63123456789abcde"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASC...你的金鑰內容...+A==\\n-----END PRIVATE KEY-----\\n"
client_email = "driven-actor-service@driven-actor-456302-e7.iam.gserviceaccount.com"
client_id = "109312345678901234567"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/driven-actor-service@driven-actor-456302-e7.iam.gserviceaccount.com"
